steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/mind-bloom-backend:$COMMIT_SHA"
      - "."
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/mind-bloom-backend:$COMMIT_SHA"
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "mind-bloom-backend"
      - "--image"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/mind-bloom-backend:$COMMIT_SHA"
      - "--region"
      - "${_REGION}"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--set-env-vars"
      - "NODE_ENV=production"

substitutions:
  _REGION: "us-central1"
  _REPOSITORY: "mind-bloom"

images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/mind-bloom-backend:$COMMIT_SHA"
